Repository buildo/avenger, pull requests merged in 2019-06, with the labels that each got.

#185 No more travis
  .travis.yml
  ci/pipeline.yml
  ci/test.sh
  ci/test.yml
Labels: in review

#183 180 dsl 2
  test/CachedQuery.test.ts
  test/Compose.test.ts
  test/utils/StatefulFetch.ts
  test/utils/testFetch.test.ts
  test/utils/testFetch.ts
Labels: WIP, in review

#190 Plantuml
  docs/Cached Value.svg
  docs/Uncached or Error Value.svg
  docs/cachedValueFlow.puml
  docs/uncachedValueFlow.puml
Labels: WIP
